docs:
  - any-glob-to-any-file: "docs/**"
contracts:
  - any-glob-to-any-file: "packages/contracts/**"
flutter:
  - any-glob-to-any-file: "apps/lifeready_flutter/**"
services:
  - any-glob-to-any-file: "services/**"
ci:
  - any-glob-to-any-file: ".github/workflows/**"
