name: Bug report
description: Report a problem in LifeReady SA
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened, and what did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the issue.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Any relevant logs or screenshots.
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: Git commit SHA or tag.
    validations:
      required: false
