name: Feature request
description: Suggest an improvement to LifeReady SA
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem are we trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How should this work?
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact and scope
      description: Who is affected and how?
    validations:
      required: false
